Repository liquity/dev, pull requests merged in 2021-06, with the labels that each got.

#588 fix: eliminate bogus `TroveChange` upon capped liquidation
  packages/subgraph/src/entities/Trove.ts
  packages/subgraph/src/mappings/BorrowerOperations.ts
  packages/subgraph/src/mappings/TroveManager.ts
  packages/subgraph/subgraph.yaml.js
Labels: bug, subgraph

#589 Fix price in subgraph
  packages/contracts/contracts/TestContracts/PriceFeedTestnet.sol
  packages/lib-subgraph/apollo.config.js
  packages/lib-subgraph/src/SubgraphLiquity.ts
  packages/lib-subgraph/types/Global.ts
  packages/lib-subgraph/types/TroveWithoutRewards.ts
  packages/subgraph/schema.graphql
  packages/subgraph/src/calls/PriceFeed.ts
  packages/subgraph/src/entities/Change.ts
  packages/subgraph/src/entities/Global.ts
  packages/subgraph/src/entities/LqtyStake.ts
  packages/subgraph/src/entities/StabilityDeposit.ts
  packages/subgraph/src/entities/SystemState.ts
  packages/subgraph/src/entities/Transaction.ts
  packages/subgraph/src/entities/Trove.ts
  packages/subgraph/src/entities/User.ts
  packages/subgraph/src/mappings/PriceFeed.ts
  packages/subgraph/src/mappings/TroveManager.ts
  packages/subgraph/src/utils/bignumbers.ts
  packages/subgraph/subgraph.yaml.js
Labels: bug, subgraph

#598 contracts: Fix simulation tests
  packages/contracts/brownie-config.yaml
  packages/contracts/tests/simulation_test.py
Labels: backend, testing

#603 contracts: Add balancer pool deployment script
  packages/contracts/hardhat.config.mainnet-fork.js
  packages/contracts/mainnetDeployment/ABIs/ERC20.js
  packages/contracts/mainnetDeployment/ABIs/IVault.js
  packages/contracts/mainnetDeployment/ABIs/WETH.js
  packages/contracts/mainnetDeployment/ABIs/WeightedPool2Tokens.js
  packages/contracts/mainnetDeployment/ABIs/WeightedPool2TokensFactory.js
  packages/contracts/mainnetDeployment/balancerPoolDeployment.js
Labels: backend

#626 contracts: Balancer pool deployment last tweaks
  packages/contracts/hardhat.config.js
  packages/contracts/mainnetDeployment/balancerDeploymentOutput/balancerOutput_20210629.txt
  packages/contracts/mainnetDeployment/balancerPoolDeployment.js
Labels: backend
